### ISSUE TITLE
Use Github workflows for building jekyll site

### ISSUE THREAD

**Issue by jeffreytse** [MolSSI-Education/2020-software-fellow-posters#24] opened 2020-07-01 04:01 UTC
Hi @janash 

I found some section of your site not showing well (e.g. [Post table header](http://education.molssi.org/2020-software-fellow-posters/sina-mostafanejad/)), and it's the building issue. 
For using any other third-party plugins, it's necessary to use CI (Github Action) for automatically building jekyll site.

So I suggest you as bellow:
1. Checkout current `gh-pages` branch files to a `master` branch, then set master branch as default branch on Github repository. 
```
git checkout -b master
git push
```

(i.e. The `gh-pages` branch is only for the site static files and the `master` branch is for source code)

2. Use a Github action for CI. [See here](https://github.com/jeffreytse/2020-software-fellow-posters)

(I also can commit a PR for u if you have checkout a `master` branch)

3. After this, create a [Personal Token](https://github.com/settings/tokens) with repos permissions for CI.
* Go to your repository’s Settings and then the Secrets tab.
* Create a token named `GH_TOKEN` (important). Give it a value using the value copied above.

**Comment by jeffreytse** [comment] 2020-07-01 04:18
Hi @janash 

* Here is a screenshot of the table currently:

![image](https://user-images.githubusercontent.com/9413601/86202171-1def5700-bb94-11ea-97ac-c37c5c1c932a.png)

* After using the CI action:

![image](https://user-images.githubusercontent.com/9413601/86202427-c43b5c80-bb94-11ea-8d34-04c7ef187e64.png)

**Comment by janash** [comment] 2020-07-01 11:43
Hi @jeffreytse - thanks for the heads up on this. Can you tell me if code block are rendering correctly on your rebuilt site? I noticed that locally my code blocks are not correct (and this difference may be why). For example the "User defined Analysis Methods" on this page - http://education.molssi.org/2020-software-fellow-posters/bradley-dice/

Should look like this:
![image](https://user-images.githubusercontent.com/18010556/86240030-6b58cd80-bb6e-11ea-8670-7718aec5e6c7.png)

**Comment by janash** [comment] 2020-07-01 12:17
Hi @jeffreytse - after some investigation, I believe the that there becomes a problem with code blocks when lines end with a colon (`:`). This is a problem because Python code (which we will have many samples of) uses colons at the end of `for` and `if` statements. Do you have any suggestions for how to fix this and use `Jekyll-spaceship`?

**Comment by janash** [comment] 2020-07-01 12:24
@SinaMostafanejad - tagging you on this as well since your poster is having the problem.

**Comment by jeffreytse** [comment] 2020-07-01 12:39
Hi @janash 

Thanks for your test, and now I'm testing it, any progress I will keep update here.

**Comment by SinaMostafanejad** [comment] 2020-07-01 12:48
> @SinaMostafanejad - tagging you on this as well since your poster is having the problem.

I'm on the watch for this repository and I have been following all changes. Let me know if this remains a problem. 

The last option would be removing the plugin for the time being and the extra features from that one table. 
It might make sense to remove the plugin from Gemfile if nobody else needs extra features provided by it (complex table processing, inline diagrams, videos etc.). 

Let me know if we reach at that point. I can commit a less complicated version of the table.

**Comment by jeffreytse** [comment] 2020-07-01 12:58
Hi @janash @SinaMostafanejad 

This issue is addressed, and I'll release a new version, then you can keep the features for abundant data presentation totally.

**Comment by janash** [comment] 2020-07-01 13:21
🎉 - so this issue should be fixed soon? Let us know what/how to update. @jeffreytse 

There is a second slightly smaller problem as well. In Latex formulas (for use with MathJax), there are problems when `|` characters are used. This can be avoided by using `\vert` (I think) instead of `|`, but many people use `|` in their formulas.

**Comment by jeffreytse** [comment] 2020-07-01 13:25
Hi, @janash 

Yes, the first one is a liquid tag filter issue, it will be fixed asap, and the second one also can be fixed, I need to do this one by one. Thanks for your good test.

Thanks with regards.

**Comment by janash** [comment] 2020-07-02 11:50
Issues added. 👍

**Comment by jeffreytse** [comment] 2020-07-02 11:52
Hi @janash, @SinaMostafanejad 

Now the first code block issue, and the second one math expression issue were fixed.
And You can have a further test for the CI building.

Thanks and regards.

**Comment by janash** [comment] 2020-07-02 21:21
Hi @jeffreytse - I'm having another issue now. Now when I try building the site, I get the error

`jekyll 3.8.7 | Error:  premature end of char-class: /\[([^\n]*)\]\s*\[JEKYLL@70142762989800@0]\lbrace \psi\rbrace[JEKYLL@70142762989800@1\]/`

Any ideas?

**Comment by SinaMostafanejad** [comment] 2020-07-02 21:56
I have reproduced the error and fixed it by making the following change after theory section, line 2:

$$\lbrace \psi\rbrace$**$:**   ---> $$\lbrace \psi\rbrace$**$ :**

* a space is needed between dollar sign and colon.

**Comment by janash** [comment] 2020-07-02 22:06
@SinaMostafanejad - on your poster? Is it fine if I update it, or do you want to do a PR?

**Comment by SinaMostafanejad** [comment] 2020-07-02 22:28
> @SinaMostafanejad - on your poster? Is it fine if I update it, or do you want to do a PR?

Yup. I actually checked another poster at first where the compile apperently stoped but found nothing.
Then I grep'ed part of the error and it turned out to be in my poster and colon after dollar signs was my first candidate to check for a parsing error.

It is fine if you update the file. Thanks!

**Comment by janash** [comment] 2020-07-02 23:45
Hi @jeffreytse - we've fixed all problems, I think, but I'm having trouble with GitHub Actions. I tried it on a fork. I generated the secret token and added it as instructed, but it is still not working (https://github.com/janash/2020-software-fellow-posters/runs/832604520)

**Comment by janash** [comment] 2020-07-03 00:50
Nevermind - I had missed setting the permissions for the token.

**Closed** 2020-07-03 01:04 UTC
